name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    name: Run eslint scanning and tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: |
          npm install 

      - name: Run ESLint
        run: npm run lint
        continue-on-error: false

      - name: Run tests
        run: CI=true npm test
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      # Runs a single command using the runners shell
    - name: Yandex Cloud CR "Login" Action for GitHub Actions
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    - name: Build, tag, and push image to Yandex Cloud Container Registry
      env:
        CR_REGISTRY: crpd4ql1b9d7h0epib57
        CR_REPOSITORY: cicd-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
        docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG# Runs a single command using the runners shell
